# Generated by Django 4.0.5 on 2022-11-26 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acount_name', models.CharField(max_length=20)),
                ('acount_unicName', models.CharField(max_length=20, unique=True)),
                ('acount_description', models.TextField(blank=True, default='Estou usando o Vekor :D', max_length=25)),
                ('acount_photo', models.ImageField(default='default/default_perfil.png', upload_to='images-perfil/')),
                ('acount_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_user1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_user1', to='chat.acount')),
                ('chat_user2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_user2', to='chat.acount')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='Grupo', max_length=20)),
                ('group_description', models.TextField(blank=True, max_length=1000)),
                ('group_photo', models.ImageField(default='default/default_group.png', upload_to='images-group/')),
                ('group_admins', models.ManyToManyField(blank=True, related_name='group_admins', to='chat.acount')),
                ('group_users', models.ManyToManyField(related_name='group_users', to='chat.acount')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(blank=True, max_length=10000)),
                ('message_visualize', models.BooleanField(default=False)),
                ('message_posted_at', models.DateTimeField(auto_now_add=True)),
                ('message_edited_at', models.DateTimeField(auto_now=True)),
                ('message_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('message_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.acount')),
                ('message_views', models.ManyToManyField(blank=True, related_name='message_views', to='chat.acount')),
            ],
        ),
    ]
