# Generated by Django 4.0.5 on 2022-12-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='acount_oneSignalId',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
