# Generated by Django 4.1.4 on 2022-12-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_acount_acount_notificated'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='images-chat/'),
        ),
    ]
