# Generated by Django 4.1.4 on 2022-12-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messages_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acount',
            name='acount_notificated',
        ),
        migrations.AddField(
            model_name='acount',
            name='acount_notifyId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
