# Generated by Django 4.1.4 on 2022-12-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_acount_acount_notificated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acount',
            name='acount_notifyId',
        ),
    ]
