# Generated by Django 4.1.4 on 2023-01-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_acount_acount_notifyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='acount_darkTheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acount',
            name='acount_private',
            field=models.BooleanField(default=False),
        ),
    ]
