# Generated by Django 4.1.4 on 2023-01-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_acount_acount_darktheme_acount_acount_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='acount_darkTheme',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='acount',
            name='acount_private',
            field=models.BooleanField(),
        ),
    ]
