# Generated by Django 4.1.4 on 2023-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_acount_acount_darktheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='acount_oneSignalId',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
